#!/bin/sh

branch=`git rev-parse --abbrev-ref HEAD`

cd ./`git rev-parse --show-cdup`

if [ "$branch" = "master" ]
then
    git checkout github
    git fetch origin
    git reset --hard origin/github

    gitignore=`cat .gitignore`

    git rebase master

    while [ $? -gt 0 ]
    do
        git reset HEAD
        rm -f $gitignore
        git rm $gitignore
        git add .gitignore
        git rebase --continue
    done

    git push -f git@github.com:wwu-housing/schedule github:master
    git checkout master
fi
